Core_AuthWithMasterdetail/Core_Auth/Controllers/PlantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core_Auth.Data;
using Core_Auth.Models;
using Microsoft.AspNetCore.Hosting;
using Core_Auth.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace Core_Auth.Controllers
{

    //[Authorize(Roles ="ADMIN,EMPLOYEE")]
    //[Authorize(Policy = "Plantshop")]
    //[Authorize(Roles ="ADMIN")]
    [Authorize(Roles ="Admin,Stuff")]
    public class PlantsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _he;

        public PlantsController(ApplicationDbContext context, IWebHostEnvironment  he)
        {
            _context = context;
            _he = he;
        }

        
        public  IActionResult Index()
        {
            return View(_context.Plants.Include(x => x.StockEntries).ThenInclude(b => b.pot).ToList());

            //var applicationDbContext = _context.Plants.Include(p => p.PlantSize);
            //return View(await applicationDbContext.ToListAsync());
        }

        public IActionResult AddNewPot(int? id)
        {
            ViewBag.pots = new SelectList(_context.pots.ToList(), "potId", "potName", id.ToString() ?? "");
            return PartialView("_AddNewpot");
        }

        //[Authorize(Policy = "Plantshop")]
        public IActionResult Create()
        {
            ViewData["SizeId"] = new SelectList(_context.plantSizes.ToList(), "SizeId", "SizeType");
            return View();

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Policy = "Plantshop")]
        public async Task<IActionResult> Create(PlantVM  plantVM, int[] potId)
        {
            if (ModelState.IsValid)
            {
                Plant plant = new Plant()
                {
                    PlantName = plantVM.PlantName,
                    StockDate=plantVM.StockDate,
                    Quantity = plantVM.Quantity,
                    SizeId=plantVM.SizeId,
                    IsAvaible = plantVM.IsAvaible,
                    
                };
                //Img
                string webroot = _he.WebRootPath;
                string folder = "Images";
                string imgFileName = Path.GetFileName(plantVM.PictureFile.FileName);
                string fileToWrite = Path.Combine(webroot, folder, imgFileName);

                using (var stream = new FileStream(fileToWrite, FileMode.Create))
                {
                    await plantVM.PictureFile.CopyToAsync(stream);
                    plant.Picture = "/" + folder + "/" + imgFileName;
                }
                foreach (var item in potId)
                {
                    StockEntry stockEntry = new StockEntry()
                    {
                        Plant = plant,
                        PlantId = plant.PlantId,
                        potId = item
                    };
                    _context.stockEntries.Add(stockEntry);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();

        }

    
        public  IActionResult Edit(int? id)
        {
            Plant plant = _context.Plants.First(x => x.PlantId == id);
            var potList = _context.stockEntries.Where(x => x.PlantId == id).Select(x => x.potId).ToList();

            ViewData["SizeId"] = new SelectList(_context.plantSizes.ToList(), "SizeId", "SizeType");

            PlantVM plantVM = new PlantVM
            {
                PlantId = plant.PlantId,
                PlantName = plant.PlantName,
                StockDate = plant.StockDate,
                Quantity = plant.Quantity,
                Picture=plant.Picture,
                SizeId= plant.SizeId,
                IsAvaible = plant.IsAvaible,
                potList = potList
            };
            return View(plantVM);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PlantVM plantVM, int[] potId)
        {

            if (ModelState.IsValid)
            {
                Plant plant = new Plant()
                {
                    PlantId=plantVM.PlantId,
                    PlantName = plantVM.PlantName,
                    StockDate = plantVM.StockDate,
                    Quantity = plantVM.Quantity,
                    SizeId = plantVM.SizeId,
                    IsAvaible = plantVM.IsAvaible,
                    Picture=plantVM.Picture

                };
                //Img
                if (plantVM.PictureFile !=null)
                {
                    string webroot = _he.WebRootPath;
                    string folder = "Images";
                    string imgFileName = Path.GetFileName(plantVM.PictureFile.FileName);
                    string fileToWrite = Path.Combine(webroot, folder, imgFileName);

                    using (var stream = new FileStream(fileToWrite, FileMode.Create))
                    {
                        await plantVM.PictureFile.CopyToAsync(stream);
                        plant.Picture = "/" + folder + "/" + imgFileName;
                    }
                }

                //exists spotList
                var existspot = _context.stockEntries.Where(x => x.PlantId == plantVM.PlantId).ToList();
                foreach (var item in existspot)
                {
                    _context.stockEntries.Remove(item);
                }
                foreach (var item in potId)
                {
                    StockEntry stockEntry = new StockEntry()
                    {
                       
                        PlantId = plant.PlantId,
                        potId = item
                    };
                    _context.stockEntries.Add(stockEntry);
                }
                _context.Entry(plant).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();

        }

    
        public async Task<IActionResult> Delete(int? id)
        {


            Plant plant = _context.Plants.First(x => x.PlantId == id);
            var spotList = _context.stockEntries.Where(x => x.PlantId == id).ToList();

            foreach (var item in spotList)
            {
                _context.stockEntries.Remove(item);
            }
            _context.Entry(plant).State = EntityState.Deleted;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

     

        
    }
}

Core_AuthWithMasterdetail/Core_Auth/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Core_Auth.Data;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Core_Auth.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
       
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;

        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(string userrole)
        {
            string msg = "";
            if (!string.IsNullOrEmpty(userrole))
            {
                if (await _roleManager.RoleExistsAsync(userrole))
                {
                    msg = "Role [" + userrole + "] already exists!!!";
                }
                else
                {
                    IdentityRole r = new IdentityRole(userrole);
                    await _roleManager.CreateAsync(r);
                    msg = "Role [" + userrole + "] has been create successfully!!!!!!!";
                }
            }
            else
            {
                msg = "Please enter a valid role name!!";
            }
            ViewBag.msg = msg;
            return View("Index");
        }
        //[Authorize(Roles = "ADMIN")]
        public IActionResult AssignRole()
        {
            ViewBag.users = _userManager.Users;
            ViewBag.roles = _roleManager.Roles;
            ViewBag.msg = TempData["msg"];
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AssignRole(string userdata, string roledata)
        {
            string msg = "";
            if (!string.IsNullOrEmpty(userdata) && !string.IsNullOrEmpty(roledata))
            {
                ApplicationUser u = await _userManager.FindByEmailAsync(userdata);
                if (u != null)
                {
                    if (await _roleManager.RoleExistsAsync(roledata))
                    {
                        await _userManager.AddToRoleAsync(u, roledata);
                        msg = "Role has been assign to user!!!";
                    }
                    else
                    {
                        msg = "Role does not exist!!!";
                    }
                }
                else
                {
                    msg = "User not found!!!";
                }
            }
            else
            {
                msg = "Please select a valid user or role!!!";
            }
            ViewBag.msg = msg;
            return RedirectToAction("AssignRole");
        }
    }
}

Core_AuthWithMasterdetail/Core_Auth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core_Auth</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script>
        function LoadSpot(potId = null) {

            var potContainer = $("#PotContainer");

            $.ajax({
                url: "/Plants/AddNewPot/" + potId ?? "",
                type: "GET",
                success: function (data) {
                    potContainer.append(data);
                }
            });
        }

        $(document).on("click", "#btnPlus", function (e) {
            e.preventDefault();
            LoadSpot();
        });

        $(document).on("click", "#btnDelete", function (e) {
            e.preventDefault();
            $(this).parent().parent().remove();
        });

    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Core_Auth</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role Management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="AssignRole">Assign Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plants" asp-action="Index">Plant</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Core_Auth - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>